### ISSUE TITLE
Eiffel protocol MVP

### ISSUE THREAD

**Issue by Andrey9kin** [Ericsson/eiffel#1]
I have a question regarding the scope of the protocol. There are quite many event types listed in the README but does it make sense to start with that many? I mean perhaps it would be better to narrow down scope so we can get the first usable version of protocol faster?

For instance, take EiffelActivityQueuedEvent. I have a hard time imagining use case and most importantly a good way of implementing a good way to send those correctly. Are they even used?
Perhaps it makes sense to start with the few core event and skip corner cases?
I mean it must be 20% of events that cover 80% of use cases, isn't it? Shall we define those first and then, if there is a need, look into more complicated cases?

**Comment by d-stahl-ericsson** [comment]
It's absolutely possible to start with a small "core" set of events and only use those: a key principle is freedom in _which_ events to use, but not in _how_ you use them. We're going to focus on such a subset of events for the first "drop" or milestone: all Artifact events, all Activity events and ConfidenceLevelModified.

So to answer your question: absolutely, but EiffelActivityQueuedEvent is a poor example. If you're going to use Activity events, you're going to need ActivityQueued. But it is of course possible to forego that.

**Comment by d-stahl-ericsson** [comment]
Proposal: Change names of ActivityQueued and ActivityDequeued to ActivityTriggered and ActivityCanceled. Triggering is always relevant, even if you don't queue. If you do queue, however, it becomes implicitly clear from the fact that there's a time delta between Triggered and Started.

**Comment by d-stahl-ericsson** [comment]
Yep, that's what we'll do.
