### ISSUE TITLE
Terminology: contextual confidence levels

### ISSUE THREAD

**Issue by rogpers-ericsson** [Ericsson/eiffel#111]
Confidence levels can be set on artifacts and baselines which is a rather straightforward thing.

A more complex scenario is when artifacts are included in other artifacts.

1. Assume some "leaf artifact" L. Various confidence levels may then be associated with L.
2. L-artifacts are built into a aggregated/higher order artifact A.
3. Various confidence levels may be associated with A (as for L in 1 above).
4. In some scenarios you want to find the latest L that was built into an A and where A has some particular confidence level.

Should we have some defined term for this kind of contextual confidence level, i.e. that L has worked (or not) in some particular context?

Some words that comes to mind: Contextual, Implied, Derived ... Confidence Level.

**Comment by d-stahl-ericsson** [comment]
That's what I would think of as Derived Confidence Level. An explicit term for it is probably a good idea. That would make it clear that the intention is not to apply the same confidence level to L simply because it was applied to A. And it's the sort of thing you probably want to provide a service for: show me all Derived Confidence Levels for L.

**Comment by d-stahl-ericsson** [comment]
So, following up on this, do you have a tangible proposal for how to do that? We currently don't have any vocabulary per se, apart from the events themselves.

**Comment by rogpers-ericsson** [comment]
I will create a pull-request for this, once I figure out where to do it.

**Comment by rogpers-ericsson** [comment]
I plan to come with an update the coming days.

**Comment by d-stahl-ericsson** [comment]
Since we closed the PR for this, I think we can close the issue?
