### ISSUE TITLE
I have an issue on the defintion on the EiffelEnvironmentDefinedEvent that I would like disucssed here

### ISSUE THREAD

**Issue by erobged** [Ericsson/eiffel#118]
Hi @d-stahl-ericsson @p-backman-ericsson @ebopalm 
Today we disucssed the EiffelEnvironmentDefinedEvent in a meeting.
This github "issue"  that I have created is a feature of the WoW in github.
It will also allow us to disucss collaborate on a topic/issue - we can use it to make proposals to the event , create a pull requests,  and then finally a decision to merge at the end.

So please reply with discussion topics.

**Comment by erobged** [comment]
Hi Bo @ebopalm ,
Here is the comment box to propose changes , discuss ideas etc... 
Regards,
Rob

**Comment by d-stahl-ericsson** [comment]
Status on this? Can I close the issue?

**Comment by ebopalm** [comment]
Yes, i think it can be closed. 
My 5 cents on the topic is that Environment and Artifcts are both part of the Orchestrating activities. Simply speaking Environment + Artifact = Service. We will continue to need and use Environment definition but also add some kind of Service related event to represent the entire Service as this resource has to be maintained on a life cycle perspective.

**Comment by d-stahl-ericsson** [comment]
It is not entirely clear to me what the concrete impact of that is. I trust that this will be covered in the work in eiffel-operations-extension or in more specific new issues in this repo, however. Closing as recommended.
