### ISSUE TITLE
New "name" property to be added in EiffelTestExecutionRecipeCollectionCreatedEvent "selection strategy"

### ISSUE THREAD

**Issue by egbomol** [Ericsson/eiffel#144]
An optional property "name", can be really useful for the test executors to handle the TERCs more efficiently. 
Pull request has already been created:
https://github.com/Ericsson/eiffel/pull/143

**Comment by d-stahl-ericsson** [comment]
Since there is already an id property and a uri property, do we really need a name property as well? We need to be very clear on how this differs from the properties already available. TestCaseTriggered doesn't have a name property, for instance, only id and uri.

**Comment by e-backmark-ericsson** [comment]
I tend to agree with Daniel, even though this was my suggestion from the beginning :)
Having the selectionStrategy.name field in this object would probably duplicate information that should already be available in the test management system. The name should be possible to retrieve by a simple call to the test management system, based on the current information in the selectionStrategy object within the TERC event.
A rule of thumb in Eiffel is to not duplicate information, but instead point to it.

**Comment by d-stahl-ericsson** [comment]
Ok, then we close this? Any other input?
