### ISSUE TITLE
Design Guideline violation in EiffelTestExecutionRecipeCollectionCreatedEvent example

### ISSUE THREAD

**Issue by egbomol** [Ericsson/eiffel#149]
Hi,

The data.batches.recipes.constraints has the following description:

Type: Object
Required: No
Description: Any constraints of the execution. The syntax of this object is not controlled, as the nature of such constraints are highly dependent on technology domain and test execution framework. That being said, there are three questions that typically need to be answered: what is the item under test, in what kind of environment is it to be tested, and what are the test parameters?

In the batches.json we have the following:

"constraints": { 
              "load": 10000, 
             "environment": { 
                "os": "ubuntu-15.04", 
               "MY_PATH": "/home/lt-worf" 
           } 
        } 

Which looks to violate the Event design Guidelines  ( https://github.com/Ericsson/eiffel/blob/master/eiffel-syntax-and-usage/event-design-guidelines.md ) paragraph:

"Do not use variable key names: For purposes of automated validation, analysis and search, custom key names shall be avoided. Consequently, for custom key-value pairs  { "key": "customKeyName", "value": "customValue" }  shall be used instead of  { "customKeyName": "customValue" } ."

The correct example should be:
"constraints": [ 
             {"key": "load", "value": 10000}, 
             {"key": "environment", "value": { 
                "os": "ubuntu-15.04", 
               "MY_PATH": "/home/lt-worf"} 
           } 
        ] 

Br,
Gabor

**Comment by d-stahl-ericsson** [comment]
Quite right. I suggest we create a version 2.0.0 of the event and change the type of data.batches.recipes.constraints to an array, as dictated by the guidelines.
