### ISSUE TITLE
EiffelTestCaseStartedEvent sample missing TEST_CASE_EXECUTION link

### ISSUE THREAD

**Issue by lmcstbi** [Ericsson/eiffel#165]
See: https://github.com/Ericsson/eiffel/blob/master/examples/events/EiffelTestCaseStartedEvent/simple.json 

According to https://github.com/Ericsson/eiffel/blob/master/eiffel-syntax-and-usage/the-links-object.md the TEST_CASE_EXECTUION link is required for this event.

**Comment by d-stahl-ericsson** [comment]
Good catch, thanks! Would you be willing to post a PR fixing the example?
