### ISSUE TITLE
Should multiple FLOW_CONTEXT links be allowed?

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel#170]
The documentation currently says multiple FLOW_CONTEXT links aren't allowed. It appears reasonable that multiple overlapping contexts should be allowed. Any downsides to that?

Discuss!

**Comment by erobged** [comment]
We have disucssed this and it is agreed that multiple FLOW_CONTEXT  should be allowed.
@l-ohlen-ericsson  will make updates and pull request.

**Comment by d-stahl-ericsson** [comment]
Right, so let's make a PR. But #136 is a prerequisite.

**Comment by l-ohlen-ericsson** [comment]
Resolved
