### ISSUE TITLE
meta.version -> data.version

### ISSUE THREAD

**Issue by Andrey9kin** [Ericsson/eiffel#21]
Current event structure consists of 3 parts - links, meta, data.
As far as I understand meta.version describes version of the data object not the meta object, right?
Should we move it to the data object then? In this way, we will be able to define version as a constant for the corresponding data class and read it from there when creating data object.
What do you think?

**Comment by d-stahl-ericsson** [comment]
Version applies to not only the data object. It's definitely part of the event meta data.

**Comment by Andrey9kin** [comment]
How about having a version for the both then? So we have distinct version for the meta structure and data structure?

**Comment by d-stahl-ericsson** [comment]
I'm sorry, I guess I'm being slow. But I really don't see how that would be an improvement? Think of the meta object as an envelope, describing the body (data). I'd much rather have the version on the envelope.

**Comment by Andrey9kin** [comment]
Perhaps we read description differently. This is how I read it - event consists of 3 data structures - meta, payload, links:

```
event {
  meta { ... }
  data { ... }
  links { ... } 
}
```
In this way, it makes sense to have version of all three types of structures so if meta changes then we step version for meta only once instead of updating all events.

If meta is an envelope then message structure description should be adjusted accordingly.

**Comment by d-stahl-ericsson** [comment]
I disagree. Separate versions for each object within the message would get very messy. Then you have to be ready to combine different versions of data with different versions of meta and links... Version constellations which would be different for every type of message. I believe what we have now is the simplest structure:

meta contains meta information: which type and version of message, where did it come from, when was it sent etc. This is the same for every type.
data contains the type specific payload.
links contains links to other events, which is also the same for every type (except some links are required/legal in some types, and not in others)

**Comment by Andrey9kin** [comment]
@d-stahl-ericsson fine. This is not a stopping issue for me - I'm using protobuf to implement messages and it won't work this way in this particular implementation but I can use protobuf built-in methods to solve this. When do you leave for the weekend on Friday? I can do a short demo of the current best thinking

**Comment by d-stahl-ericsson** [comment]
@Andrey9kin Friday at 12 works for me. Send me a request if that works for you.
