### ISSUE TITLE
EiffelTestExecutionRecipeCreatedEvent

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel#41]
Documentation and example required.

**Comment by d-stahl-ericsson** [comment]
Internal workshop review input: Given the current structure, assuming 10k recipes the event will end up on the order of 5MB, which is bad. It should be a protocol design principle that events should not contain properties of highly variable size which is likely to cause very large event sizes.

For this particular event, the conclusion is that the TERC needs to be externally stored and linked via uri. However, a recommended format shall be provided (similar to what is currently proposed in the event).

**Comment by e-backmark-ericsson** [comment]
👍
