### ISSUE TITLE
data.category vs data.categories in ActivityTriggered and TestSuiteStarted

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel#55]
Sketching a proposal of TestSuiteStarted, I realized that an array data.categories would be more helpful than a string data.category. Given that, the same should apply to ActivityTriggered.

Thoughts?

**Comment by rogpers-ericsson** [comment]
From a genericity perspective an array would be better.

**Comment by d-stahl-ericsson** [comment]
Putting it differently, is there a perspective from which it would be worse?

**Comment by rogpers-ericsson** [comment]
Not that I can see.
