### ISSUE TITLE
TERC link type and TestSuiteStarted

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel#56]
A thought. We have currently defined that TestCaseStarted can use TERC links. Another option is to move it to TestSuiteStarted, dictating that if you execute based on a TERC you group your test cases as a single TestSuite, which references that TERC.

Thoughts?

**Comment by e-backmark-ericsson** [comment]
I'd like to agree on that any test case originating from a TERC should also be part of a test suite on some level. Thus it would be fair to move the TERC link to the TestSuiteStarted event. You could still group test cases in a TERC into several test suites (even hierarchical) if needed/wanted.
So yes, I'd vote for moving the TERC link option from TestCaseStarted to TestSuiteStarted.
