### ISSUE TITLE
Should/could Test(Suite)Started events reference ActivityTriggered?

### ISSUE THREAD

**Issue by e-backmark-ericsson** [Ericsson/eiffel#68]
I see some dis-alignment in how we define TestCase/Suite events in relation to Activity events. I'm reviewing the event flow in usage-examples/confidence-level-joining.md

According to the picture the TestCase executions are not considered a subclass of Activities, since they don't use the same types of links. Both ActivityStarted and ActivityFinished have ACTIVITY_EXECUTION links to the ActivityTriggered event, but in the TestCase case there is instead a CONTEXT link from TestCaseStarted towards ActivityTriggered and then a TEST_CASE_EXECUTION link from TestCaseFinished towards TestCaseStarted.

I see two ways:
- TestCase(/Suite) executions should be considered a subclass of Activities, and thereby using ACTIVITY_EXECUTION links from both TestCase(/Suite)Started and TestCase(/Suite)Finished towards ActivityTriggered.
- TestCase(/Suite) executions should be considered a lower leveled 'thing' and should instead use a CONTEXT link from TestCase(/Suite)Started to ActivityStarted (and no link to ActivityTriggered)

If we say that TestCase(/Suite) executions are a subclass of Activities we also open the door for introducing BuildStarted/BuildFinished events in the same way going forward.

If we don't define either/or I think we give too much freedom to the users of the protocol. It would make it harder to implement visualization and measurement solutions on the Eiffel protocol then.

**Comment by d-stahl-ericsson** [comment]
The idea of *_EXECUTION is to group the tuples signifying the beginning and the end (and in the case of Activity, the triggering) of something, whereas CONTEXT declares what (if anything) it was part of. So the intention is in line with your second bullet - the only difference being that the link target ActivityTriggered instead of ActivityStarted. I personally don't have any strong opinion either way - the reason for using ActivityTriggered is that it's the first event, but ActivityStarted makes sense, too.

**Comment by e-backmark-ericsson** [comment]
Is it out of question to introduce sub-classing of events? I can see benefits in saying that EiffelTest*Events are subclasses of EiffelActivity*Events. The same way we could introduce similar events for other activities, such as Build, Deliver, Deploy and Release for example. Those events would then inherit the properties of the EiffelActivity*Events and extend them with properties specific to the activity they represent.

In the same way we could for example probably introduce a superclass for all Eiffel*DefinedEvents.

Fewer top-class event types cater for a simpler event structure that is easier to understand, extend and manage.

**Comment by d-stahl-ericsson** [comment]
Let's sketch a concrete proposal together and see what that would look like in practice.

**Comment by d-stahl-ericsson** [comment]
We haven't done anything about this yet. Emil, will you take the initiative on this?

**Comment by e-backmark-ericsson** [comment]
This is not yet sorted out. I will re-open it or open a new issue when I have a suggestion to provide.
