### ISSUE TITLE
Specify version in the JSON schema

### ISSUE THREAD

**Issue by p-backman-ericsson** [Ericsson/eiffel#76]
The JSON schemas only specify the pattern for the version of the event. It would be good to be able to validate/generate the version itself. 

Should we change the version to an enum specifying the version the schema specifies?

Changing:

```
"version": {
  "type": "string",
  "pattern": "^(\\d+\\.)(\\d+\\.)(\\d+)$"
},
```

To:

```
"version": {
  "enum": [ "1.0.0" ]
},
```

**Comment by d-stahl-ericsson** [comment]
In principle you could do that, but if you're going to specify explicit versions, then what does a list of versions mean? Presumably the event has changed between those versions, so only one of them will actually be valid according to the schema.

Now the version is implicitly the latest in the same Git revision. I'm not saying that's the best solution, but an enum I can't quite wrap my head around. If we want to tighten it, then it should be a single value (e.g. "1.0.0"), and then you could keep historical versions (i.e. for every new version of a message you create another schema file, each with an explicit version).

**Comment by p-backman-ericsson** [comment]
I was thinking of an enum with only one value. If we are to build code based on these schemas it is good if the version is stated in the schema. Otherwise we risk sending a version 1.0.2 event with version set to 1.0.3... 

I think enum with one value is the best way of restricting the version. Perhaps we should add a default keyword as well to help serializers.

    "version": {
      "type": String,
      "enum": [ "1.5.5" ],
      "default": "1.5.5."
    },

If we want to keep all old versions we need to device some naming scheme for the schemas and perhaps put then in a sub folder.

**Comment by d-stahl-ericsson** [comment]
That makes sense then. Yes, you would need a directory structure for it. E.g. rather than

schemas/EventType.json

you would have

schemas/EventType/version.json

and when you went about validating a specific event you'd first have to look up its version, then go pick the appropriate schema. Will require some work, but makes sense to me.
