### ISSUE TITLE
Colloquial name property in ArtifactCreated

### ISSUE THREAD

**Issue by d-stahl-ericsson** [Ericsson/eiffel#84]
The need for providing a non-canonical name of artifacts has been put forward. Sometimes GAVs are rather cryptic or non-descriptive, and then a colloquial, non-canonical name is valuable.

I see very little reason in not including it as an optional property, and would suggest data.colloquialName. Thoughts?

**Comment by a-wensmark-ericsson** [comment]
I think it should be part of the data.gav data structure, or even better, replace the **data.gav** structure with a **data.artifact** structure instead. The GAV is very limited and does not work very well. This is what I propose:

- data.artifact.artifactId    (_Required_)
      This should be the product number of an artifact or something that uniquely identifies it.

- data.artifact.version    (_Required_)

- data.artifact.**artifactName**  (_Optional_)
      A human understandable name of the artifact.

- data.artifact.**type**  (_Optional_) 
      This could be a list of strings that tells the type of the artifact, e.g. LoadModule, Interphase, Tool, etc

- data.artifact.groupId

**Comment by p-backman-ericsson** [comment]
Could we use a simpler term then colloquial? I like the simplicity of artifactName if used in a gav context. Although I think it should be data.artifact.name if we would go for that approach.

**Comment by d-stahl-ericsson** [comment]
Sure, we can skip colloquial and make that fact implicit. "artifact" as a prefix is redundant, so simply "name" should do just fine.

If we're going to add type, is there any reasonable way we can standardize/enumerate that? Any way we can avoid free text strings? :)

GAV is a widely used and well understand concept, and should be preserved. Adding properties to it isn't helpful. So it's going to be
data.gav
data.name
data.types (?)

**Comment by a-wensmark-ericsson** [comment]
If the **name** and the **type** isn’t tied to the artifact there is a big risk that no one know what these fields are to be used for! One of the reasons for 2.0 was to avoid being ambiguous! 

I do not agree that concept of GAV is widely used; widely used by Maven of course but not beyond that. I do not see anything stopping us from defining our own Artifact data structure. The “GAV” parts are still in there!

**Comment by d-stahl-ericsson** [comment]
The properties would be in ArtifactCreated. Any properties within its data object refer to the artifact. You can mentally append "of the artifact" to every property: "gav of the artifact", "name of the artifact" et cetera.

GAV is supported by all the major repository managers, by Ivy, Gradle, Maven, Buildr, SBT... For identifying distributed dependencies, I'd argue it's the closest thing we have to a standard.

**Comment by a-wensmark-ericsson** [comment]
Yes, and the common denominator is Java. For all other non-java artifacts, GAV is unknown. Besides, I do not see why Eiffel have to be so tied to a  Maven vocabulary. We do have a lot of other types of products that is not Java based. It would make a lot more sense to have a wider Artifact identification data structure.

The reason why I think it is better to group it in an Artifact identification object and not to have it separate is because then you can easily handle data that goes together in an easy way, both in terms of implementation and in data structures. Having name and type on the top level would be the same as having “data.fileInformation.extension” as just “data.extension” and still keep the “data.fileInformation” object. The GAV is an artifact identification object, which is lacking name and type and maybe even more things! Let’s create an artifact identification object that is more practical and which can be expanded if needed!

**Comment by d-stahl-ericsson** [comment]
I see your point. But still, whatever one might think of it, GAV is a standard, and so long as we do use it we shouldn't do violence to it by adding custom properties to it. Because then we're not following any standard at all.

Regarding the Java community. Despite having its roots there, the standard is applicable and increasingly used outside of Java, and I still prefer following a (albeit not ubiquitous) standard than following no standard. Allowing for more than one is of course an alternative (see e.g. handling of SCM systems in SourceChangeCreatedEvent) to consider - would you like to propose a competing alternative to GAV?

**Comment by a-wensmark-ericsson** [comment]
I would not like to propose a competing alternative to the GAV data structure, it would be ridiculous to have two structures having almost the same content. Instead I think we should treat the “GAV” in the same way as Maven, Nexus, etc. does where the “GAV” is not an object. It is just three data fields which are not grouped together. Eiffel should follow this standard. It is only in Eiffel that the groupId, ArtifactId and Version is put in a separate data structure – the “GAV”. This does not add value. It only makes implementation harder. Let’s get rid of this data structure and the limitations that it enforces will go away.
•  data.groupId
•  data.artifactId 
•  data.version 
•  data.name 
•  data.contentTypes 
etc...

**Comment by d-stahl-ericsson** [comment]
I don't have a strong opinion either way, but there are many ways of expressing GAVs. To exemplify, Ivy does
`<dependency org="commons-lang" name="commons-lang" rev="2.0"/>`
and Gradle does
`'org.springframework:spring-core:2.5'`
or
`[group: 'org.springframework', name: 'spring-core', version: '2.5']`

The only common denominator is that the unique identifier consists of three parts. Then they can be expressed at the root of the POM or as a string or in a separate object or an array or whatever.

**Comment by a-wensmark-ericsson** [comment]
Then, you have just proven that there is no standard for how a “GAV” should be expressed, so my arguments still stand. Let’s not use a ”GAV” sub structure for reason of simplicity. A substructure does not add any value and it complicates triggering and implementation, for reasons I’m not allowed to explain.

**Comment by d-stahl-ericsson** [comment]
Sorry, but that makes no sense to me. This thread has gone far enough off topic already, so let's end it there: continuing this thread isn't going to lead to a resolution. Feel free to bring it up in front of a whiteboard if this is a serious issue, then we take it from there.

Returning to the original topic, as already raised in PR #77 and then implemented in PR #89, properties for name and type are valid additions to ArtifactCreated. Closing the thread.
